### ISSUE TITLE
The find users section doesn't show any users on Firefox

### ISSUE THREAD

**Issue by keitho2000** [nicolaschan/market#1]
The find users section is blank on Firefox. It doesn't show any users even if I search for them.

**Comment by keitho2000** [comment]
![2015-10-13-113708_1366x768_scrot](https://cloud.githubusercontent.com/assets/13408533/10464494/dceb537e-719e-11e5-8fb4-867760a3003a.png)

**Comment by safelock** [comment]
Cannot reproduce. Maybe missing view assets or not dl properly? (GTK?) Running Firefox 41.0.1
![capture](https://cloud.githubusercontent.com/assets/1351429/10464688/ed8e7048-719f-11e5-8744-20b7faa96523.PNG)

**Comment by keitho2000** [comment]
I'm running Iceweasel 38.2.1. I don't think GTK would affect this, Firefox uses the gecko rendering engine.

**Comment by safelock** [comment]
Do you have JS enabled? Seems like webcontent has many js, not to mention the majority of the code is js.
