### ISSUE TITLE
Quick Search Doesn't Work with Current Release

### ISSUE THREAD

**Issue by safelock** [nicolaschan/market#2]
Quicklinks do not look up items properly. Found out on Firefox 41 and Chrome 45.
Steps to reproduce:
1. Create an item and obtain its quicklink ID. (Set to buy or not buy, doesn't matter).
2. Login under another account, and attempt to search for the item. (It'll give a response saying not found.)
Images will be uploaded very shortly.

**Comment by safelock** [comment]
![screen shot 2015-10-13 at 12 51 00 pm](https://cloud.githubusercontent.com/assets/1351429/10466482/594eec00-71a9-11e5-8d37-8e36173e5497.png)
![screen shot 2015-10-13 at 12 51 26 pm](https://cloud.githubusercontent.com/assets/1351429/10466483/59531f28-71a9-11e5-9d41-fb0a8215ef3f.png)
![screen shot 2015-10-13 at 12 51 38 pm](https://cloud.githubusercontent.com/assets/1351429/10466484/5960f9c2-71a9-11e5-9783-97606e46cf7e.png)

**Comment by safelock** [comment]
NVM, Index Error.

**Comment by nicolaschan** [comment]
This happens when the quicklink index file is out of sync with the database and can be fixed by increasing the index file (such as by creating items) until it is back in sync.
